In [1]:
import numpy
array= numpy.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [2]:
import numpy
array= numpy.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [5]:
import numpy as np

# Creating NumPy Arrays
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
zeros = np.zeros((3, 4))
ones = np.ones((2, 2))
identity_matrix = np.eye(3)

# Array Operations
result_add = arr_1d + 10
result_multiply = arr_1d * 2
result_sqrt = np.sqrt(arr_1d)
result_dot_product = np.dot(arr_2d, np.array([2, 2, 2]))
result_comparison = arr_1d > 3

# Array Indexing and Slicing
element = arr_1d[2]
sub_array = arr_1d[1:4]
value = arr_2d[1, 2]
sub_matrix = arr_2d[:, 1:3]

# Array Aggregation and Statistics
mean = np.mean(arr_1d)
total = np.sum(arr_1d)
max_value = np.max(arr_1d)
min_index = np.argmin(arr_1d)

# Reshaping Arrays
reshaped = arr_1d.reshape((5, 1))  # Reshape to a compatible shape
flattened = arr_2d.flatten()

# Random Number Generation
random_numbers = np.random.rand(3, 3)
random_integers = np.random.randint(1, 10, size=(2, 2))

# Printing results
print("1D Array:", arr_1d)
print("2D Array:", arr_2d)
print("Zeros Array:")
print(zeros)
print("Ones Array:")
print(ones)
print("Identity Matrix:")
print(identity_matrix)

print("Result of Element-wise Addition:", result_add)
print("Result of Element-wise Multiplication:", result_multiply)
print("Result of Element-wise Square Root:", result_sqrt)
print("Result of Matrix Multiplication (dot product):", result_dot_product)
print("Result of Element-wise Comparison (arr_1d > 3):", result_comparison)

print("Accessed Element (arr_1d[2]):", element)
print("Sliced Array (arr_1d[1:4]):", sub_array)
print("Accessed Value (arr_2d[1, 2]):", value)
print("Sliced Matrix (arr_2d[:, 1:3]):")
print(sub_matrix)

print("Mean of arr_1d:", mean)
print("Sum of arr_1d:", total)
print("Maximum Value in arr_1d:", max_value)
print("Index of Minimum Value in arr_1d:", min_index)

print("Reshaped Array (5x1):")
print(reshaped)
print("Flattened 2D Array:")
print(flattened)

print("Random Numbers (3x3):")
print(random_numbers)
print("Random Integers (2x2):")
print(random_integers)


1D Array: [1 2 3 4 5]
2D Array: [[1 2 3]
 [4 5 6]]
Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
[[1. 1.]
 [1. 1.]]
Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Result of Element-wise Addition: [11 12 13 14 15]
Result of Element-wise Multiplication: [ 2  4  6  8 10]
Result of Element-wise Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Result of Matrix Multiplication (dot product): [12 30]
Result of Element-wise Comparison (arr_1d > 3): [False False False  True  True]
Accessed Element (arr_1d[2]): 3
Sliced Array (arr_1d[1:4]): [2 3 4]
Accessed Value (arr_2d[1, 2]): 6
Sliced Matrix (arr_2d[:, 1:3]):
[[2 3]
 [5 6]]
Mean of arr_1d: 3.0
Sum of arr_1d: 15
Maximum Value in arr_1d: 5
Index of Minimum Value in arr_1d: 0
Reshaped Array (5x1):
[[1]
 [2]
 [3]
 [4]
 [5]]
Flattened 2D Array:
[1 2 3 4 5 6]
Random Numbers (3x3):
[[0.80636943 0.19555589 0.64034778]
 [0.69651248 0.82747907 0.06985091]
 [0.4224718  0.77388892 0.26761704]]
Random In

In [7]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [9]:
import numpy as np

# Sample data
X = np.array([1, 2, 3, 4, 5])
Y = np.array([2, 3, 4, 5, 6])

# Calculate the mean of X and Y
mean_X = np.mean(X)
mean_Y = np.mean(Y)

# Calculate the differences between data points and the means
diff_X = X - mean_X
diff_Y = Y - mean_Y

# Calculate the slope (beta1) and intercept (beta0)
beta1 = np.sum(diff_X * diff_Y) / np.sum(diff_X ** 2)
beta0 = mean_Y - (beta1 * mean_X)

# Predict Y values using the linear regression model
Y_pred = beta0 + beta1 * X

# Print the regression coefficients
print("Intercept (beta0):", beta0)
print("Slope (beta1):", beta1)

# Predicted values
print("Predicted Y values:", Y_pred)


Intercept (beta0): 1.0
Slope (beta1): 1.0
Predicted Y values: [2. 3. 4. 5. 6.]


In [10]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [12]:
from numpy import random

x = random.randint(100)

print(x)

48


In [13]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[84 30 13 41  8]


In [14]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))

print(x)

[5 7 5 5 7 7 5 3 7 7 3 5 7 3 7 7 5 5 7 3 5 5 7 5 3 5 7 5 5 7 5 7 5 7 5 3 3
 7 7 5 7 7 3 5 7 5 7 5 3 7 5 7 7 5 5 7 7 7 7 7 5 3 7 5 7 7 5 7 7 7 7 7 7 7
 3 5 5 7 7 7 7 5 5 5 7 7 5 5 7 5 7 3 7 5 7 7 7 3 7 7]


In [15]:
from numpy import random

x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))

print(x)

[[7 5 7 7 7]
 [5 7 7 7 7]
 [5 7 7 7 5]]
